#!/usr/bin/env guile
!#

;;; SPDX-FileCopyrightText: 2022 Brian Kubisiak <brian@kubisiak.com>
;;;
;;; SPDX-License-Identifier: GPL-3.0-only

(use-modules (sagittarius)
             (sagittarius path)
             (sagittarius subprocess))

(define (load-config)
  (eval-string
   (string-join
    (check-call git
                "-C"
                (home "sagittarius-config")
                "cat-file"
                "--textconv"
                "master:config.scm")
    "\n")))

(define* (main #:optional (args (command-line)))
  (apply sagittarius-main (cons load-config args)))

(main)
